chore(x2a): bump permissions version (#2220)
Because container image failed to build:

```
 ========== Exporting backend plugin plugins/x2a-backend ==========
  > npx --yes @red-hat-developer-hub/cli@1.9.1 plugin export --embed-package @red-hat-developer-hub/backstage-plugin-x2a-common
Error running CLI: Building embedded package @red-hat-developer-hub/backstage-plugin-x2a-common in /home/runner/work/rhdh-plugin-export-overlays/rhdh-plugin-export-overlays/source-repo/workspaces/x2a/plugins/x2a-common
  executing     yarn build ✔
Packing embedded package @red-hat-developer-hub/backstage-plugin-x2a-common in /home/runner/work/rhdh-plugin-export-overlays/rhdh-plugin-export-overlays/source-repo/workspaces/x2a/plugins/x2a-common to embedded/red-hat-developer-hub-backstage-plugin-x2a-common
Customizing embedded package @red-hat-developer-hub/backstage-plugin-x2a-common for dynamic loading
  moving @backstage/plugin-permission-common to peerDependencies
Building main package
  executing     yarn build ✔
Packing main package to dist-dynamic/package.json
Customizing main package in dist-dynamic/package.json for dynamic loading
  moving @backstage/backend-defaults to peerDependencies
  moving @backstage/backend-openapi-utils to peerDependencies
  moving @backstage/backend-plugin-api to peerDependencies
  moving @backstage/catalog-client to peerDependencies
  moving @backstage/errors to peerDependencies
  moving @backstage/plugin-auth-backend to peerDependencies
  moving @backstage/plugin-auth-backend-module-github-provider to peerDependencies
  moving @backstage/plugin-auth-backend-module-guest-provider to peerDependencies
  moving @backstage/plugin-catalog-backend to peerDependencies
  moving @backstage/plugin-catalog-node to peerDependencies
  moving @backstage/plugin-permission-common to peerDependencies
  moving @backstage/types to peerDependencies
Hoisting peer dependencies of embedded packages to the main package
Error: The version of a dependency ('@backstage/plugin-permission-common') of an embedded module conflicts with main module dependencies: '^0.9.4', '^0.9.3': cannot proceed!
Plugins with failed exports: plugins/x2a-backend
```

Signed-off-by: Eloy Coto <eloy.coto@acalustra.com>