chore(x2a): move k8s client to dynamic import
When I run `npx @red-hat-developer-hub/cli plugin export` I got this:

```
Error: Unable to validate plugin entry points: Error [ERR_REQUIRE_ESM]: require() of ES Module /home/eloy/dev/upstream/redhat-developer/plugins-test/workspaces/x2a/plugins/x2a-backend/dist-dynamic/node_modules/@kubernetes/client-node/dist/index.js from /home/eloy/dev/upstream/redhat-developer/plugins-test/workspaces/x2a/plugins/x2a-backend/dist-dynamic/dist/services/makeK8sClient.cjs.js not supported.
Instead change the require of index.js in /home/eloy/dev/upstream/redhat-developer/plugins-test/workspaces/x2a/plugins/x2a-backend/dist-dynamic/dist/services/makeK8sClient.cjs.js to a dynamic import() which is available in all CommonJS modules.
```

With these changes, I can happily export the plugin:

```
$ -> npx @red-hat-developer-hub/cli plugin export
Building embedded package @red-hat-developer-hub/backstage-plugin-x2a-common in /home/eloy/dev/upstream/redhat-developer/plugins-test/workspaces/x2a/plugins/x2a-common
  executing     yarn build ✔
Packing embedded package @red-hat-developer-hub/backstage-plugin-x2a-common in /home/eloy/dev/upstream/redhat-developer/plugins-test/workspaces/x2a/plugins/x2a-common to embedded/red-hat-developer-hub-backstage-plugin-x2a-common
Customizing embedded package @red-hat-developer-hub/backstage-plugin-x2a-common for dynamic loading
  moving @backstage/plugin-permission-common to peerDependencies
Building main package
  executing     yarn build ✔
Packing main package to dist-dynamic/package.json
Customizing main package in dist-dynamic/package.json for dynamic loading
  moving @backstage/backend-defaults to peerDependencies
  moving @backstage/backend-openapi-utils to peerDependencies
  moving @backstage/backend-plugin-api to peerDependencies
  moving @backstage/catalog-client to peerDependencies
  moving @backstage/errors to peerDependencies
  moving @backstage/plugin-auth-backend to peerDependencies
  moving @backstage/plugin-auth-backend-module-github-provider to peerDependencies
  moving @backstage/plugin-auth-backend-module-guest-provider to peerDependencies
  moving @backstage/plugin-catalog-backend to peerDependencies
  moving @backstage/plugin-catalog-node to peerDependencies
  moving @backstage/plugin-permission-common to peerDependencies
  moving @backstage/types to peerDependencies
Hoisting peer dependencies of embedded packages to the main package
Installing private dependencies of the main package
  executing     yarn install --immutable > yarn-install.log ✔
Validating private dependencies
Validating plugin entry points
Saving self-contained config schema in /home/eloy/dev/upstream/redhat-developer/plugins-test/workspaces/x2a/plugins/x2a-backend/dist-dynamic/dist/configSchema.json and /home/eloy/dev/upstream/redhat-developer/plugins-test/workspaces/x2a/plugins/x2a-backend/dist-dynamic/dist/.config-schema.json
Filling supported-versions with 1.45.0.
```

Signed-off-by: Eloy Coto <eloy.coto@acalustra.com>