fix(x2a): fix when running on openshift
To avoid this:

```

$ -> oc -n x2ansible logs -f job-x2a-init-30d126bd-zhxnt
==========================================
  X2A init Phase
==========================================

Job Configuration:
  Project ID:    4dde21dd-b8a8-403c-ad6e-1e2aac3c9f67
  Project Abbrev: myprj
  Module ID:     N/A
  Module Name:   N/A
  Job ID:        bf0bca2b-5dd6-49f6-a05f-02df0d907f91
  Phase:         init

error: could not lock config file //.gitconfig: Permission denied
Reporting result: status=error, phase=init
error: Failed to initialize cache at `/.cache/uv`
  Caused by: failed to create directory `/.cache/uv`: Permission denied (os error 13)
WARNING: Failed to report result to backend
```

Signed-off-by: Eloy Coto <eloy.coto@acalustra.com>